### ISSUE TITLE
gap between 'svg > path' (about section)

### ISSUE THREAD

**Issue by fwttnnn** [jhrfadhil/Simple-website-using-Bootstrap-5-and-jQuery#4]
![issue](https://user-images.githubusercontent.com/74759624/115700201-f8675000-a355-11eb-9347-8162f85e4786.png)

**Comment by jhrfadhil** [comment]
![Capture](https://user-images.githubusercontent.com/77342457/115703207-0b007a00-a394-11eb-92de-36c5ef4310f0.PNG)

There is no gap in my browser

**Comment by fwttnnn** [comment]
![a](https://user-images.githubusercontent.com/74759624/115703628-dec80780-a359-11eb-96e4-3af1b4bce9bf.png)


a slight gap will appear around 800 - 1000px width
